import jsPDF from 'jspdf'

/**
 * Export the 2D canvas to PNG
 */
export function exportToPNG(
  canvasElement: HTMLCanvasElement,
  filename: string = 'floor-plan.png'
) {
  const link = document.createElement('a')
  link.download = filename
  link.href = canvasElement.toDataURL('image/png')
  link.click()
}

/**
 * Export the floor plan to PDF with stats
 */
export function exportToPDF(
  canvasElement: HTMLCanvasElement,
  warehouseName: string,
  stats: {
    totalArea: number
    utilization: number
    palletCapacity: number
    itemCount: number
    doorCount?: number
  }
) {
  const pdf = new jsPDF('landscape', 'mm', 'a4')
  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()

  // Header
  pdf.setFillColor(15, 23, 42) // slate-900
  pdf.rect(0, 0, pageWidth, 35, 'F')

  // Title
  pdf.setTextColor(255, 255, 255)
  pdf.setFontSize(20)
  pdf.setFont('helvetica', 'bold')
  pdf.text(`Floor Plan: ${warehouseName}`, 14, 18)

  // Subtitle
  pdf.setFontSize(10)
  pdf.setFont('helvetica', 'normal')
  pdf.text(`Generated: ${new Date().toLocaleString()}`, 14, 28)

  // Stats box
  pdf.setFillColor(30, 41, 59) // slate-800
  pdf.roundedRect(14, 42, pageWidth - 28, 25, 3, 3, 'F')

  pdf.setTextColor(255, 255, 255)
  pdf.setFontSize(11)

  const statsY = 52
  const colWidth = (pageWidth - 28) / 4

  // Stat 1: Total Area
  pdf.setFont('helvetica', 'bold')
  pdf.text('Total Area', 20, statsY)
  pdf.setFont('helvetica', 'normal')
  pdf.text(`${stats.totalArea.toLocaleString()} sq ft`, 20, statsY + 8)

  // Stat 2: Utilization
  pdf.setFont('helvetica', 'bold')
  pdf.text('Utilization', 20 + colWidth, statsY)
  pdf.setFont('helvetica', 'normal')
  pdf.text(`${stats.utilization}%`, 20 + colWidth, statsY + 8)

  // Stat 3: Pallet Capacity
  pdf.setFont('helvetica', 'bold')
  pdf.text('Pallet Capacity', 20 + colWidth * 2, statsY)
  pdf.setFont('helvetica', 'normal')
  pdf.text(`${stats.palletCapacity} pallets`, 20 + colWidth * 2, statsY + 8)

  // Stat 4: Items
  pdf.setFont('helvetica', 'bold')
  pdf.text('Equipment Items', 20 + colWidth * 3, statsY)
  pdf.setFont('helvetica', 'normal')
  pdf.text(`${stats.itemCount} items${stats.doorCount ? `, ${stats.doorCount} doors` : ''}`, 20 + colWidth * 3, statsY + 8)

  // Canvas image
  const imgData = canvasElement.toDataURL('image/png')
  const imgWidth = pageWidth - 28
  const aspectRatio = canvasElement.height / canvasElement.width
  const imgHeight = imgWidth * aspectRatio
  const maxImgHeight = pageHeight - 85

  const finalHeight = Math.min(imgHeight, maxImgHeight)
  const finalWidth = finalHeight / aspectRatio

  // Center the image
  const imgX = 14 + (imgWidth - finalWidth) / 2

  pdf.addImage(imgData, 'PNG', imgX, 72, finalWidth, finalHeight)

  // Footer
  pdf.setFillColor(15, 23, 42)
  pdf.rect(0, pageHeight - 12, pageWidth, 12, 'F')
  pdf.setFontSize(8)
  pdf.setTextColor(148, 163, 184) // slate-400
  pdf.text('Generated by Warebnb Floor Plan Designer', 14, pageHeight - 5)
  pdf.text('www.warebnb.co', pageWidth - 14, pageHeight - 5, { align: 'right' })

  // Save
  const safeFilename = warehouseName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')

  pdf.save(`floor-plan-${safeFilename || 'warehouse'}.pdf`)
}

/**
 * Export 3D view screenshot using html2canvas
 */
export async function export3DScreenshot(
  containerElement: HTMLElement,
  filename: string = 'floor-plan-3d.png'
) {
  // Dynamically import html2canvas to avoid SSR issues
  const html2canvas = (await import('html2canvas')).default

  const canvas = await html2canvas(containerElement, {
    backgroundColor: '#0f172a',
    scale: 2,
    logging: false,
    useCORS: true
  })

  const link = document.createElement('a')
  link.download = filename
  link.href = canvas.toDataURL('image/png')
  link.click()
}
