alter table if exists public.warehouse_floors
add column if not exists name text not null default 'Floor',
add column if not exists floor_level integer not null default 1,
add column if not exists length_m numeric not null default 50,
add column if not exists width_m numeric not null default 30,
add column if not exists height_m numeric not null default 10,
add column if not exists wall_clearance_m numeric not null default 0.5,
add column if not exists sprinkler_clearance_m numeric not null default 0.9,
add column if not exists safety_clearance_m numeric not null default 0.5,
add column if not exists main_aisle_m numeric not null default 3.5,
add column if not exists side_aisle_m numeric not null default 2.5,
add column if not exists pedestrian_aisle_m numeric not null default 1.0,
add column if not exists loading_zone_depth_m numeric not null default 3.0,
add column if not exists dock_zone_depth_m numeric not null default 4.5,
add column if not exists standard_pallet_height_m numeric not null default 1.5,
add column if not exists euro_pallet_height_m numeric not null default 1.5,
add column if not exists custom_pallet_length_cm numeric not null default 100,
add column if not exists custom_pallet_width_cm numeric not null default 100,
add column if not exists custom_pallet_height_cm numeric not null default 150,
add column if not exists stacking_override integer,
add column if not exists status boolean not null default true;
